#Q1C: Find if a certain stop contains accessibility information
#eg: d1 %STOPID acc_4_107_288
#eg: d5 %STOPID 00000000000000000007

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX gtfs: <http://vocab.gtfs.org/terms#>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX gtfsstop: <http://linkedgtfs.com/CITY/stops/>

SELECT * WHERE {
	gtfsstop:00000000000000000007 a gtfs:Stop . 
	gtfsstop:00000000000000000007 dct:description ?stopDescription . 
	gtfsstop:00000000000000000007 geo:lat ?stopLat . 
	gtfsstop:00000000000000000007 geo:long ?stopLong . 
	OPTIONAL { gtfsstop:00000000000000000007 gtfs:wheelchairBoarding ?stopWheelchairBoarding .  }
}
