PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX mpv: <http://mappingpedia.linkeddata.es/vocabulary#>

SELECT ?a ?n ?e ?w
WHERE { 
   ?a mpv:name ?n .
   OPTIONAL {
      ?a mpv:email ?e .
      OPTIONAL {?a mpv:webpage ?w .}
   }
}
