#Q1C: Find if a certain stop contains accessibility information
#vig.q1c.STOPID=00000000000000000005

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX gtfs: <http://vocab.gtfs.org/terms#>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX gtfsstop: <http://linkedgtfs.com/CITY/stops/>

SELECT * WHERE {
	gtfsstop:00000000000000000005 a gtfs:Stop . 
	gtfsstop:00000000000000000005 dct:description ?stopDescription . 
	gtfsstop:00000000000000000005 geo:lat ?stopLat . 
	gtfsstop:00000000000000000005 geo:long ?stopLong . 
	OPTIONAL { gtfsstop:00000000000000000005 gtfs:wheelchairBoarding ?stopWheelchairBoarding .  }
}
