#Q2C: Check the number of routes of a particular agency
#vig.q2c.AGENCYID=00000000000000000002

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX gtfs: <http://vocab.gtfs.org/terms#>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX gtfsagency: <http://linkedgtfs.com/CITY/agency/>

SELECT (count(distinct ?route) as ?nRoutes) WHERE {
	gtfsagency:00000000000000000002 a gtfs:Agency .
	gtfsagency:00000000000000000002 foaf:page ?agencyPage .
	gtfsagency:00000000000000000002 foaf:name ?agencyName .
	OPTIONAL { gtfsagency:00000000000000000002 foaf:phone ?agencyPhone . }

	?route a gtfs:Route .
	?route gtfs:agency gtfsagency:00000000000000000002 .
}
