#Q3C: Given a particular stop, get the list of arrival times of vehicles going a particular direction
#vig.q3c.STOPID=00000000000000000007
#vig.q3c.HEADSIGN="00000000000000000033"

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX gtfs: <http://vocab.gtfs.org/terms#>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX gtfsstop: <http://linkedgtfs.com/CITY/stops/>

SELECT * WHERE {

        ?stopTime a gtfs:StopTime .
        ?stopTime gtfs:trip ?trip .
        ?stopTime gtfs:stop gtfsstop:00000000000000000007 .
        ?stopTime gtfs:arrivalTime ?arrivalTime .

        ?trip a gtfs:Trip .
        ?trip gtfs:shortName ?tripShortName .
        ?trip gtfs:service ?service .
        ?trip gtfs:route ?route .
        ?trip gtfs:headsign "Opera" .

        gtfsstop:00000000000000000007 a gtfs:Stop .
        OPTIONAL { gtfsstop:00000000000000000007 dct:description ?stopDescription . }

}
