#Q13: All the accesses of a specific station.
#original.q11.STOPNAME='Nuevos Ministerios'
#vig.q11.STOPNAME='000000000000000000sm'

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX gtfs: <http://vocab.gtfs.org/terms#>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX gtfslocation: <http://transport.linkeddata.es/resource/LocationType/>


SELECT  *
WHERE {     
    ?stop a gtfs:Stop .
    ?stop gtfs:parentStation ?parStation .
    OPTIONAL {?stop foaf:name ?accName} .
    ?stop gtfs:locationType gtfslocation:2 .
    ?parStation a gtfs:Stop .
    ?parStation foaf:name '000000000000000000sm'      
}
