#Q15: Everything that contains a specific string in the object placeholder (any property)
#original.q15.STOPSTR='Doctor'
#vig.q15.STOPSTR='000000000000000002ag'

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX gtfs: <http://vocab.gtfs.org/terms#>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX dct: <http://purl.org/dc/terms/>

SELECT * 
#FROM <http://gtfs1.linkeddata.es>
WHERE { 
	?stop a gtfs:Stop .
	?stop ?p ?str .
	FILTER regex (?str, '000000000000000002ag')
}
