#Q16: For all the routes, all the calendar changes during a specific month
#original.q16.STARTDATE='2017-03-01'
#original.q16.ENDDATE='2017-03-31'
#vig.q16.STARTDATE='2017-03-01'
#original.q16.ENDDATE='2017-03-31'

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX gtfs: <http://vocab.gtfs.org/terms#>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT * 
# FROM <http://gtfs1.linkeddata.es>
WHERE {
	?trip a gtfs:Trip .
	?trip gtfs:service ?service .
	?trip gtfs:route ?route . 

#	?route gtfs:longName ?longName .

        ?service a gtfs:Service .
        ?service gtfs:serviceRule ?serviceRule .

        ?serviceRule a gtfs:CalendarDateRule .
        ?serviceRule  dct:date ?servDate .
        ?serviceRule  gtfs:dateAddition "true"^^xsd:boolean .
	FILTER (?servDate >= '2017-03-01'^^xsd:date) .
        FILTER (?servDate <= '2017-03-31'^^xsd:date) .

}
