docker stop morph-example-mysql
docker rm morph-example-mysql
docker rmi morph-example-mysql
docker stop drupal
docker rm drupal
docker rmi drupal
docker stop mysql-morph
docker rm mysql-morph
docker rmi mysql-morph
docker-compose up -d
