PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?loc
WHERE { 
   <http://mappingpedia.linkeddata.es/resources/department/10> a <http://example.com/Department> .
	<http://mappingpedia.linkeddata.es/resources/department/10> <http://mappingpedia.linkeddata.es/vocabulary/location4> ?loc .
}
