#Q2A: List all agencies and their routes. Datasets: Agency and Routes

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX gtfs: <http://vocab.gtfs.org/terms#>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX dct: <http://purl.org/dc/terms/>

SELECT * WHERE {
	?route a gtfs:Route .
	?route gtfs:shortName ?routeShortName .
	OPTIONAL { ?route dct:description ?routeDescription . } 
	?route gtfs:agency ?agency .
	?agency a gtfs:Agency .
	?agency foaf:page ?agencyPage .
	?agency foaf:name ?agencyName .
	OPTIONAL { ?agency foaf:phone ?agencyPhone . }
}
