#Q10: Number of trips offered by a specific route that have a duration over 30 minutes
#original.q10.ROUTEID=4__1___
#original.q10.DEPARTURETIME="00:30:00"
#vig.q10.ROUTEID=00000000000000000008
#vig.q10.DEPARTURETIME="00:30:00"

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX gtfs: <http://vocab.gtfs.org/terms#>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX gtfsroute: <http://transport.linkeddata.es/madrid/metro/routes/>

SELECT (count(distinct ?trip) as ?count)  WHERE {
	?route a gtfs:Route .

	?trip a gtfs:Trip .
	?trip gtfs:route ?route .

	?stopTime a gtfs:StopTime . 
	?stopTime gtfs:trip ?trip . 
	?stopTime gtfs:departureTime ?departureTime .

	FILTER (?route=gtfsroute:4__1___) .
	FILTER (?departureTime >= "00:30:00"^^xsd:duration) .
}
