#q2ad number of stops that are wheelchair-accessible grouped by route


PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX gtfs: <http://vocab.gtfs.org/terms#>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?longName (count(?name) as ?count)
WHERE { 	
	?route a gtfs:Route .
	?route gtfs:longName ?longName .
 
	?trip a gtfs:Trip .
	?trip gtfs:route ?route .
 
	?stopTime a gtfs:StopTime .
	?stopTime gtfs:trip ?trip .
	?stopTime gtfs:stop ?stop .
 
 	?stop a gtfs:Stop .
 	?stop foaf:name  ?name .
 	?stop gtfs:locationType '0' .
 	?stop gtfs:wheelchairBoarding "true"^^xsd:boolean	
}
GROUP BY ?longName
