#q6ad For all the routes all the schedule changes during December

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX gtfs: <http://vocab.gtfs.org/terms#>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT * 
# FROM <http://gtfs1.linkeddata.es>
WHERE {
	?trip a gtfs:Trip .
	?trip gtfs:service ?serv .
	?trip gtfs:route ?route .

	?route gtfs:longName ?longName . 

	?serv a gtfs:ServiceDates .
	?serv  dct:date ?servDate .
	?serv  gtfs:dateAddition true .
	FILTER (?servDate >= '2017-12-01'^^xsd:date)
}
