#Q3B: List all possible routes from a particular stop
#eg: original.q3b.STOPID=acc_4_1_1

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX gtfs: <http://vocab.gtfs.org/terms#>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX gtfsstop: <http://linkedgtfs.com/CITY/stops/>

SELECT * WHERE {
	?route a gtfs:Route .
	?route gtfs:shortName ?routeShortName .
	?route dct:description ?routeDescription .

	?trip a gtfs:Trip .
	?trip gtfs:shortName ?tripShortName .
	?trip gtfs:service ?service .
	?trip gtfs:route ?route .

	?stopTime a gtfs:StopTime . 
	?stopTime gtfs:trip ?trip . 
	?stopTime gtfs:stop gtfsstop:acc_4_1_1 . 

	gtfsstop:acc_4_1_1 a gtfs:Stop . 
	gtfsstop:acc_4_1_1 dct:description ?stopDescription . 

}
