PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT *
WHERE { 
   ?student <http://mappingpedia.linkeddata.es/vocabulary/hasSport> ?sport .
   ?sport a <http://mappingpedia.linkeddata.es/vocabulary/Sport> .
   OPTIONAL { ?sport <http://mappingpedia.linkeddata.es/vocabulary/id> ?sportId . }
   OPTIONAL { ?sport <http://mappingpedia.linkeddata.es/vocabulary/name> ?sportName . }
}

