#get relative humidity in a specific month (e.g. January)

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX epw: <http://epw.linkeddata.es/vocab#>
PREFIX epwmadrid: <http://epw.linkeddata.es/resources/madrid/>

SELECT *
WHERE { 
	?s a epw:EPW .
	?s epw:month ?month .
	?s epw:relativeHumidity ?relativeHumidity .

	FILTER (?month = 1)
}
